
# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from hooks.py and the example nodes in
# `src/pipelines/`
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/stable/04_kedro_project_setup/02_configuration.html#parameters

model_params: {criterion: "mse",
              max_depth: 12,
              min_samples_leaf: 3,
              min_samples_split: 2,
              n_estimators: 32,
              n_jobs: -1,
              random_state: 28}

seed: 28
verbose: 28


station_nes_names: ['Station_id', 'Station', 'Lat', 'Long',
                    'Dock_Count', 'City', 'Inst_date']
zip_code: {'San Francisco': 94107, 'Redwood City': 94063, 'Palo Alto': 94301,
           'Mountain View': 94041, 'San Jose': 95113}
trip_nes_names: ['Trip_ID', 'Start_Date', 'Start_Station',
                 'End_Date', 'End_Station', 'Subscriber_Type']
map_id: {85: 23, 86: 25, 87: 49, 88: 69, 89: 72, 90: 72}
mind: '2014-09-01 00:00:00'
maxd: '2015-08-31 23:00:00'
freq: 'H'
resample_list: [['Start_Station', 'Start_Date'], ['End_Station', 'End_Date']]

